/**
 * Unit tests (tsx) del PARSER de fuentes gratis (free-sources-sync · cheahjs).
 * Ejecuta:  npx tsx scripts/test-free-sources.ts
 *
 * SIN RED: el fixture de abajo es el README REAL de
 * https://raw.githubusercontent.com/cheahjs/free-llm-api-resources/main/README.md
 * descargado durante la investigación de esta tarea (2026-07-20, 26 proveedores:
 * 13 en "Free Providers" + 13 en "Providers with trial credits"). Se parsea en
 * memoria — ninguna función de este test toca la red. `refreshFreeSourcesFromLists`
 * se llama una vez para confirmar que, sin `window` (entorno Node/tsx), es SSR-safe
 * y no intenta red (las pruebas de red real quedan fuera de este script, por diseño).
 */

import {
  parseCheahjsReadme,
  slugify,
  stripMd,
  matchExistingCatalogSource,
  toSuggestion,
  getFreeSourceSuggestions,
  refreshFreeSourcesFromLists,
  CHEAHJS_README_URL,
  type ParsedFreeLlmProvider,
} from "@/ai/astraura/free-sources-sync";

let passed = 0;
let failed = 0;
function ok(name: string, cond: boolean, extra?: unknown) {
  if (cond) {
    passed++;
    console.log(`  ✓ ${name}`);
  } else {
    failed++;
    console.error(`  ✗ ${name}`, extra !== undefined ? extra : "");
  }
}
function eq(name: string, a: unknown, b: unknown) {
  ok(name, JSON.stringify(a) === JSON.stringify(b), { got: a, want: b });
}
function byName(list: ParsedFreeLlmProvider[], name: string): ParsedFreeLlmProvider | undefined {
  return list.find((p) => p.name === name);
}

// ── Fixture: README REAL de cheahjs/free-llm-api-resources (raw, descargado durante la investigación) ──
const CHEAHJS_README_FIXTURE = `<!---
WARNING: DO NOT EDIT THIS FILE DIRECTLY. IT IS GENERATED BY src/pull_available_models.py
--->
# Free LLM API resources

This lists various services that provide free access or credits towards API-based LLM usage.

> [!NOTE]  
> Please don't abuse these services, else we might lose them.

> [!WARNING]  
> This list explicitly excludes any services that are not legitimate (eg reverse engineers an existing chatbot)

- [Free Providers](#free-providers)
  - [OpenRouter](#openrouter)
  - [Google AI Studio](#google-ai-studio)
  - [NVIDIA NIM](#nvidia-nim)
  - [Mistral (La Plateforme)](#mistral-la-plateforme)
  - [Mistral (Codestral)](#mistral-codestral)
  - [HuggingFace Inference Providers](#huggingface-inference-providers)
  - [Vercel AI Gateway](#vercel-ai-gateway)
  - [OpenCode Zen](#opencode-zen)
  - [Cerebras](#cerebras)
  - [Groq](#groq)
  - [Cohere](#cohere)
  - [GitHub Models](#github-models)
  - [Cloudflare Workers AI](#cloudflare-workers-ai)
- [Providers with trial credits](#providers-with-trial-credits)
  - [Fireworks](#fireworks)
  - [Baseten](#baseten)
  - [Nebius](#nebius)
  - [Novita](#novita)
  - [AI21](#ai21)
  - [Upstage](#upstage)
  - [NLP Cloud](#nlp-cloud)
  - [Alibaba Cloud (International) Model Studio](#alibaba-cloud-international-model-studio)
  - [Modal](#modal)
  - [Inference.net](#inferencenet)
  - [Hyperbolic](#hyperbolic)
  - [SambaNova Cloud](#sambanova-cloud)
  - [Scaleway Generative APIs](#scaleway-generative-apis)

## Free Providers

### [OpenRouter](https://openrouter.ai)

**Limits:**

[20 requests/minute<br>50 requests/day<br>Up to 1000 requests/day with $10 lifetime topup](https://openrouter.ai/docs/api/reference/limits)

Models share a common quota.

- [Hermes 3 Llama 3.1 405B](https://openrouter.ai/nousresearch/hermes-3-llama-3.1-405b:free)
- [Llama 3.2 3B Instruct](https://openrouter.ai/meta-llama/llama-3.2-3b-instruct:free)
- [Llama 3.3 70B Instruct](https://openrouter.ai/meta-llama/llama-3.3-70b-instruct:free)
- [cognitivecomputations/dolphin-mistral-24b-venice-edition:free](https://openrouter.ai/cognitivecomputations/dolphin-mistral-24b-venice-edition:free)
- [cohere/north-mini-code:free](https://openrouter.ai/cohere/north-mini-code:free)
- [google/gemma-4-26b-a4b-it:free](https://openrouter.ai/google/gemma-4-26b-a4b-it:free)
- [google/gemma-4-31b-it:free](https://openrouter.ai/google/gemma-4-31b-it:free)
- [nvidia/nemotron-3-nano-30b-a3b:free](https://openrouter.ai/nvidia/nemotron-3-nano-30b-a3b:free)
- [nvidia/nemotron-3-nano-omni-30b-a3b-reasoning:free](https://openrouter.ai/nvidia/nemotron-3-nano-omni-30b-a3b-reasoning:free)
- [nvidia/nemotron-3-super-120b-a12b:free](https://openrouter.ai/nvidia/nemotron-3-super-120b-a12b:free)
- [nvidia/nemotron-3-ultra-550b-a55b:free](https://openrouter.ai/nvidia/nemotron-3-ultra-550b-a55b:free)
- [nvidia/nemotron-3.5-content-safety:free](https://openrouter.ai/nvidia/nemotron-3.5-content-safety:free)
- [nvidia/nemotron-nano-12b-v2-vl:free](https://openrouter.ai/nvidia/nemotron-nano-12b-v2-vl:free)
- [nvidia/nemotron-nano-9b-v2:free](https://openrouter.ai/nvidia/nemotron-nano-9b-v2:free)
- [openai/gpt-oss-20b:free](https://openrouter.ai/openai/gpt-oss-20b:free)
- [poolside/laguna-m.1:free](https://openrouter.ai/poolside/laguna-m.1:free)
- [poolside/laguna-xs-2.1:free](https://openrouter.ai/poolside/laguna-xs-2.1:free)
- [qwen/qwen3-coder:free](https://openrouter.ai/qwen/qwen3-coder:free)
- [qwen/qwen3-next-80b-a3b-instruct:free](https://openrouter.ai/qwen/qwen3-next-80b-a3b-instruct:free)
- [tencent/hy3:free](https://openrouter.ai/tencent/hy3:free)

### [Google AI Studio](https://aistudio.google.com)

Data is used for training when used outside of the UK/CH/EEA/EU.

<table><thead><tr><th>Model Name</th><th>Model Limits</th></tr></thead><tbody>
<tr><td>Gemini 3.5 Flash</td><td>250,000 tokens/minute<br>20 requests/day<br>5 requests/minute</td></tr>
<tr><td>Gemini 3 Flash</td><td>250,000 tokens/minute<br>20 requests/day<br>5 requests/minute</td></tr>
<tr><td>Gemini 3.1 Flash-Lite</td><td>250,000 tokens/minute<br>500 requests/day<br>15 requests/minute</td></tr>
<tr><td>Gemini 2.5 Flash</td><td>250,000 tokens/minute<br>20 requests/day<br>5 requests/minute</td></tr>
<tr><td>Gemini 2.5 Flash-Lite</td><td>250,000 tokens/minute<br>20 requests/day<br>10 requests/minute</td></tr>
<tr><td>Gemini 3.1 Flash TTS</td><td>10,000 tokens/minute<br>10 requests/day<br>3 requests/minute</td></tr>
<tr><td>Gemini 2.5 Flash TTS</td><td>10,000 tokens/minute<br>10 requests/day<br>3 requests/minute</td></tr>
<tr><td>Gemini Robotics-ER 1.6</td><td>250,000 tokens/minute<br>20 requests/day<br>5 requests/minute</td></tr>
<tr><td>Gemini Robotics-ER 1.5</td><td>250,000 tokens/minute<br>20 requests/day<br>10 requests/minute</td></tr>
<tr><td>Gemma 3 27B Instruct</td><td>15,000 tokens/minute<br>14,400 requests/day<br>30 requests/minute</td></tr>
<tr><td>Gemma 3 12B Instruct</td><td>15,000 tokens/minute<br>14,400 requests/day<br>30 requests/minute</td></tr>
<tr><td>Gemma 3 4B Instruct</td><td>15,000 tokens/minute<br>14,400 requests/day<br>30 requests/minute</td></tr>
<tr><td>Gemma 3 1B Instruct</td><td>15,000 tokens/minute<br>14,400 requests/day<br>30 requests/minute</td></tr>
</tbody></table>

### [NVIDIA NIM](https://build.nvidia.com/explore/discover)

Phone number verification required.
Models tend to be context window limited.

**Limits:** 40 requests/minute

- [Various open models](https://build.nvidia.com/models)

### [Mistral (La Plateforme)](https://console.mistral.ai/)

* Free tier (Experiment plan) requires opting into data training
* Requires phone number verification.

**Limits (per-model):** 1 request/second, 500,000 tokens/minute, 1,000,000,000 tokens/month

- [Open and Proprietary Mistral models](https://docs.mistral.ai/getting-started/models/models_overview/)

### [Mistral (Codestral)](https://codestral.mistral.ai/)

* Currently free to use
* Monthly subscription based
* Requires phone number verification

**Limits:** 30 requests/minute, 2,000 requests/day

- Codestral

### [HuggingFace Inference Providers](https://huggingface.co/docs/inference-providers/en/index)

HuggingFace Serverless Inference limited to models smaller than 10GB. Some popular models are supported even if they exceed 10GB.

**Limits:** [$0.10/month in credits](https://huggingface.co/docs/inference-providers/en/pricing)

- Various open models across supported providers

### [Vercel AI Gateway](https://vercel.com/docs/ai-gateway)

Routes to various supported providers.

**Limits:** [$5/month](https://vercel.com/docs/ai-gateway/pricing)


### [OpenCode Zen](https://opencode.ai/docs/zen/)

AI gateway with curated models.

Free models may use data for improvement.

- Big Pickle Stealth
- Nemotron 3 Super Free
- DeepSeek V4 Flash Free

### [Cerebras](https://cloud.cerebras.ai/)

<table><thead><tr><th>Model Name</th><th>Model Limits</th></tr></thead><tbody>
<tr><td>gpt-oss-120b</td><td>30 requests/minute<br>60,000 tokens/minute<br>900 requests/hour<br>1,000,000 tokens/hour<br>14,400 requests/day<br>1,000,000 tokens/day</td></tr>
<tr><td>Llama 3.1 8B</td><td>30 requests/minute<br>60,000 tokens/minute<br>900 requests/hour<br>1,000,000 tokens/hour<br>14,400 requests/day<br>1,000,000 tokens/day</td></tr>
</tbody></table>

### [Groq](https://console.groq.com)

<table><thead><tr><th>Model Name</th><th>Model Limits</th></tr></thead><tbody>
<tr><td>Allam 2 7B</td><td>7,000 requests/day<br>6,000 tokens/minute</td></tr>
<tr><td>Llama 3.1 8B</td><td>14,400 requests/day<br>6,000 tokens/minute</td></tr>
<tr><td>Llama 3.3 70B</td><td>1,000 requests/day<br>12,000 tokens/minute</td></tr>
<tr><td>Whisper Large v3</td><td>2,000 requests/day</td></tr>
<tr><td>Whisper Large v3 Turbo</td><td>2,000 requests/day</td></tr>
<tr><td>canopylabs/orpheus-arabic-saudi</td><td></td></tr>
<tr><td>canopylabs/orpheus-v1-english</td><td></td></tr>
<tr><td>groq/compound</td><td>250 requests/day<br>70,000 tokens/minute</td></tr>
<tr><td>groq/compound-mini</td><td>250 requests/day<br>70,000 tokens/minute</td></tr>
<tr><td>meta-llama/llama-prompt-guard-2-22m</td><td></td></tr>
<tr><td>meta-llama/llama-prompt-guard-2-86m</td><td></td></tr>
<tr><td>openai/gpt-oss-120b</td><td>1,000 requests/day<br>8,000 tokens/minute</td></tr>
<tr><td>openai/gpt-oss-20b</td><td>1,000 requests/day<br>8,000 tokens/minute</td></tr>
<tr><td>openai/gpt-oss-safeguard-20b</td><td>1,000 requests/day<br>8,000 tokens/minute</td></tr>
<tr><td>qwen/qwen3.6-27b</td><td>1,000 requests/day<br>8,000 tokens/minute</td></tr>
</tbody></table>

### [Cohere](https://cohere.com)

**Limits:**

[20 requests/minute<br>1,000 requests/month](https://docs.cohere.com/docs/rate-limits)

Models share a common monthly quota.

- c4ai-aya-expanse-32b
- c4ai-aya-vision-32b
- command-a-03-2025
- command-a-plus-05-2026
- command-a-reasoning-08-2025
- command-a-translate-08-2025
- command-a-vision-07-2025
- command-r-08-2024
- command-r-plus-08-2024
- command-r7b-12-2024
- command-r7b-arabic-02-2025

### [GitHub Models](https://github.com/marketplace/models)

Extremely restrictive input/output token limits.

**Limits:** [Dependent on Copilot subscription tier (Free/Pro/Pro+/Business/Enterprise)](https://docs.github.com/en/github-models/prototyping-with-ai-models#rate-limits)

- Codestral 25.01
- Cohere Command A
- DeepSeek-R1
- DeepSeek-R1-0528
- DeepSeek-V3-0324
- Llama 4 Maverick 17B 128E Instruct FP8
- Llama 4 Scout 17B 16E Instruct
- Llama-3.2-11B-Vision-Instruct
- Llama-3.2-90B-Vision-Instruct
- Llama-3.3-70B-Instruct
- Meta-Llama-3.1-405B-Instruct
- Meta-Llama-3.1-8B-Instruct
- Ministral 3B
- Mistral Medium 3 (25.05)
- Mistral Small 3.1
- OpenAI GPT-4.1
- OpenAI GPT-4.1-mini
- OpenAI GPT-4.1-nano
- OpenAI GPT-4o
- OpenAI GPT-4o mini
- OpenAI Text Embedding 3 (large)
- OpenAI Text Embedding 3 (small)
- OpenAI gpt-5
- OpenAI gpt-5-chat (preview)
- OpenAI gpt-5-mini
- OpenAI gpt-5-nano
- OpenAI o1
- OpenAI o1-mini
- OpenAI o1-preview
- OpenAI o3
- OpenAI o3-mini
- OpenAI o4-mini
- Phi-4
- Phi-4-mini-instruct
- Phi-4-mini-reasoning
- Phi-4-multimodal-instruct
- Phi-4-reasoning

### [Cloudflare Workers AI](https://developers.cloudflare.com/workers-ai)

**Limits:** [10,000 neurons/day](https://developers.cloudflare.com/workers-ai/platform/pricing/#free-allocation)

- @cf/aisingapore/gemma-sea-lion-v4-27b-it
- @cf/google/gemma-4-26b-a4b-it
- @cf/ibm-granite/granite-4.0-h-micro
- @cf/moonshotai/kimi-k2.6
- @cf/moonshotai/kimi-k2.7-code
- @cf/nvidia/nemotron-3-120b-a12b
- @cf/openai/gpt-oss-120b
- @cf/openai/gpt-oss-20b
- @cf/qwen/qwen3-30b-a3b-fp8
- @cf/zai-org/glm-4.7-flash
- @cf/zai-org/glm-5.2
- DeepSeek R1 Distill Qwen 32B
- Gemma 2B Instruct (LoRA)
- Gemma 7B Instruct (LoRA)
- Llama 2 7B Chat (LoRA)
- Llama 3.1 8B Instruct (FP8)
- Llama 3.2 11B Vision Instruct
- Llama 3.2 1B Instruct
- Llama 3.2 3B Instruct
- Llama 3.3 70B Instruct (FP8)
- Llama 4 Scout Instruct
- Llama Guard 3 8B
- Mistral 7B Instruct v0.2 (LoRA)
- Mistral Small 3.1 24B Instruct
- Qwen 2.5 Coder 32B Instruct
- Qwen QwQ 32B

</tbody></table>



## Providers with trial credits

### [Fireworks](https://fireworks.ai/)

**Credits:** $1

**Models:** [Various open models](https://fireworks.ai/models)

### [Baseten](https://app.baseten.co/)

**Credits:** $30

**Models:** [Any supported model - pay by compute time](https://www.baseten.co/library/)

### [Nebius](https://tokenfactory.nebius.com/)

**Credits:** $1

**Models:** [Various open models](https://tokenfactory.nebius.com/models)

### [Novita](https://novita.ai/?ref=ytblmjc&utm_source=affiliate)

**Credits:** $0.5 for 1 year

**Models:** [Various open models](https://novita.ai/models)

### [AI21](https://studio.ai21.com/)

**Credits:** $10 for 3 months

**Models:** Jamba family of models

### [Upstage](https://console.upstage.ai/)

**Credits:** $10 for 3 months

**Models:** Solar Pro/Mini

### [NLP Cloud](https://nlpcloud.com/home)

**Credits:** $15

**Requirements:** Phone number verification

**Models:** Various open models

### [Alibaba Cloud (International) Model Studio](https://bailian.console.alibabacloud.com/)

**Credits:** 1 million tokens/model

**Models:** [Various open and proprietary Qwen models](https://www.alibabacloud.com/en/product/modelstudio)

### [Modal](https://modal.com)

**Credits:** $5/month upon sign up, $30/month with payment method added

**Models:** Any supported model - pay by compute time

### [Inference.net](https://inference.net)

**Credits:** $1, $25 on responding to email survey

**Models:** Various open models

### [Hyperbolic](https://app.hyperbolic.ai/)

**Credits:** $1

**Models:**
- DeepSeek V3 0324
- Llama 3.3 70B Instruct
- deepseek-ai/deepseek-r1-0528
- qwen/qwen3-coder-480b-a35b-instruct

### [SambaNova Cloud](https://cloud.sambanova.ai/)

**Credits:** $5 for 3 months

**Models:**
- deepseek-v3.1
- deepseek-v3.2
- gemma-4-31b-it
- gpt-oss-120b
- meta-llama-3.3-70b-instruct
- minimax-m2.7

### [Scaleway Generative APIs](https://console.scaleway.com/generative-api/models)

**Credits:** 1,000,000 free tokens

**Models:**
- BGE-Multilingual-Gemma2
- Gemma 3 27B Instruct
- Llama 3.3 70B Instruct
- Pixtral 12B (2409)
- Whisper Large v3
- devstral-2-123b-instruct-2512
- gemma-4-26b-a4b-it
- glm-5.2
- gpt-oss-120b
- holo2-30b-a3b
- mistral-medium-3.5-128b
- mistral-small-3.2-24b-instruct-2506
- qwen3-235b-a22b-instruct-2507
- qwen3-coder-30b-a3b-instruct
- qwen3-embedding-8b
- qwen3.5-397b-a17b
- qwen3.6-35b-a3b
- voxtral-small-24b-2507


`;

async function main() {
  console.log("\n[0] Fixture — no toca red (solo texto embebido)");
  {
    ok(
      "el fixture es el README real (marca de generación de cheahjs)",
      CHEAHJS_README_FIXTURE.includes("pull_available_models.py"),
    );
    ok(
      "CHEAHJS_README_URL apunta a raw.githubusercontent.com",
      CHEAHJS_README_URL.includes("raw.githubusercontent.com/cheahjs/free-llm-api-resources"),
    );
  }

  const providers = parseCheahjsReadme(CHEAHJS_README_FIXTURE);

  console.log("\n[1] parseCheahjsReadme — conteo global (fixture real: 13 + 13)");
  {
    eq("total de proveedores", providers.length, 26);
    eq("sección 'free'", providers.filter((p) => p.section === "free").length, 13);
    eq("sección 'trial-credits'", providers.filter((p) => p.section === "trial-credits").length, 13);
    ok("nunca lanza con markdown vacío", parseCheahjsReadme("").length === 0);
    ok(
      "nunca lanza con markdown basura",
      parseCheahjsReadme("### esto no es una lista\nni tiene secciones").length === 0,
    );
    ok(
      "nunca lanza con input no-string",
      (parseCheahjsReadme as (x: unknown) => ParsedFreeLlmProvider[])(null).length === 0,
    );
  }

  console.log("\n[2] OpenRouter — viñetas de modelos + límites en enlace de párrafo siguiente");
  {
    const p = byName(providers, "OpenRouter");
    ok("existe", !!p);
    if (p) {
      eq("sección", p.section, "free");
      eq("websiteUrl", p.websiteUrl, "https://openrouter.ai");
      ok("límites capturados (20 requests/minute)", p.limitsText.includes("20 requests/minute"));
      ok("límites capturados (separador de <br>)", p.limitsText.includes("·"));
      eq("nº de modelos en viñetas", p.models.length, 20);
      ok("incluye un modelo :free conocido", p.models.some((m) => m.includes("tencent/hy3:free")));
    }
  }

  console.log("\n[3] Cerebras — tabla HTML (sin marcador **Limits:** fuera de la tabla)");
  {
    const p = byName(providers, "Cerebras");
    ok("existe", !!p);
    if (p) {
      eq("modelos de la tabla", p.models, ["gpt-oss-120b", "Llama 3.1 8B"]);
      ok(
        "limitsText sintetizado desde la tabla",
        p.limitsText.includes("tabla") && p.limitsText.includes("30 requests/minute"),
      );
    }
  }

  console.log("\n[4] Google AI Studio — tabla de 13 filas, sin **Limits:** ni viñetas");
  {
    const p = byName(providers, "Google AI Studio");
    ok("existe", !!p);
    if (p) {
      eq("nº de modelos (filas de tabla)", p.models.length, 13);
      ok("incluye Gemini 3.5 Flash", p.models.includes("Gemini 3.5 Flash"));
      ok("limitsText honesto (deriva de la tabla, no inventado)", p.limitsText.includes("13 modelos"));
    }
  }

  console.log("\n[5] Mistral (Codestral) — notas '*' → requirementsText, modelo único en viñeta '-'");
  {
    const p = byName(providers, "Mistral (Codestral)");
    ok("existe", !!p);
    if (p) {
      eq("modelos", p.models, ["Codestral"]);
      eq("límites", p.limitsText, "30 requests/minute, 2,000 requests/day");
      ok("requisitos desde viñetas '*'", p.requirementsText.includes("phone number verification"));
      ok("nota 'Currently free to use' capturada", p.requirementsText.includes("Currently free to use"));
    }
  }

  console.log("\n[6] Vercel AI Gateway y OpenCode Zen — proveedores NUEVOS (no curados)");
  {
    const vercel = byName(providers, "Vercel AI Gateway");
    ok("Vercel existe", !!vercel);
    if (vercel) {
      eq("Vercel: sin modelos listados en la fuente (honesto)", vercel.models.length, 0);
      eq("Vercel: límites", vercel.limitsText, "$5/month");
    }
    const zen = byName(providers, "OpenCode Zen");
    ok("OpenCode Zen existe", !!zen);
    if (zen) {
      eq("OpenCode Zen: sin marcador **Limits:** → limitsText vacío", zen.limitsText, "");
      eq("OpenCode Zen: 3 modelos en viñetas", zen.models.length, 3);
    }
  }

  console.log("\n[7] Fireworks (trial) y SambaNova Cloud (trial, viñetas bajo **Models:**)");
  {
    const fw = byName(providers, "Fireworks");
    ok("Fireworks existe", !!fw);
    if (fw) {
      eq("sección", fw.section, "trial-credits");
      eq("créditos", fw.creditsText, "$1");
      eq("modelo inline (enlace tras **Models:**)", fw.models, ["Various open models"]);
    }
    const sn = byName(providers, "SambaNova Cloud");
    ok("SambaNova existe", !!sn);
    if (sn) {
      eq("créditos", sn.creditsText, "$5 for 3 months");
      eq(
        "6 modelos en viñetas bajo **Models:** (no duplica la línea marcador)",
        sn.models,
        ["deepseek-v3.1", "deepseek-v3.2", "gemma-4-31b-it", "gpt-oss-120b", "meta-llama-3.3-70b-instruct", "minimax-m2.7"],
      );
    }
  }

  console.log("\n[8] stripMd — decodifica <br>, enlaces y negrita a texto plano");
  {
    eq("enlace markdown", stripMd("[20 req/min](https://x.example)"), "20 req/min");
    eq("br → separador", stripMd("a<br>b<br/>c"), "a · b · c");
    eq("negrita fuera", stripMd("**Limits:**"), "Limits:");
    eq("vacío", stripMd(""), "");
  }

  console.log("\n[9] slugify — kebab-case estable, robusto ante paréntesis y vacío");
  {
    eq("simple", slugify("OpenRouter"), "openrouter");
    eq("espacios", slugify("Google AI Studio"), "google-ai-studio");
    eq("paréntesis", slugify("Mistral (Codestral)"), "mistral-codestral");
    eq(
      "paréntesis largos",
      slugify("Alibaba Cloud (International) Model Studio"),
      "alibaba-cloud-international-model-studio",
    );
    eq("vacío → fallback", slugify(""), "fuente");
    eq("solo símbolos → fallback", slugify("!!!"), "fuente");
  }

  console.log("\n[10] matchExistingCatalogSource — cruce EXPLÍCITO contra FREE_CATALOG (13 conocidos)");
  {
    const groq = matchExistingCatalogSource("Groq");
    ok("Groq → groq-free", groq?.id === "groq-free");
    const cod = matchExistingCatalogSource("Mistral (Codestral)");
    ok("Mistral (Codestral) → mistral-free", cod?.id === "mistral-free");
    const gas = matchExistingCatalogSource("Google AI Studio");
    ok("Google AI Studio → gemini-free", gas?.id === "gemini-free");
    ok("Vercel AI Gateway → sin match (nuevo)", matchExistingCatalogSource("Vercel AI Gateway") === undefined);
    ok("OpenCode Zen → sin match (nuevo)", matchExistingCatalogSource("OpenCode Zen") === undefined);
    ok("nombre desconocido no revienta", matchExistingCatalogSource("Proveedor Que No Existe") === undefined);
  }

  console.log("\n[11] toSuggestion — forma estable para la UI, ids 'freellm-<slug>'");
  {
    const suggestions = providers.map(toSuggestion);
    eq("nº de sugerencias == nº de proveedores", suggestions.length, 26);
    ok("todas requieren clave (la lista cheahjs excluye anónimos)", suggestions.every((s) => s.requiresKey === true));
    ok("todos los ids empiezan por 'freellm-'", suggestions.every((s) => s.id.startsWith("freellm-")));
    ok("ninguna 'limits' vacía (fallback honesto)", suggestions.every((s) => !!s.limits && s.limits.length > 0));
    eq("ya curados en FREE_CATALOG", suggestions.filter((s) => s.alreadyInCatalog).length, 13);
    eq("nuevos (no curados)", suggestions.filter((s) => !s.alreadyInCatalog).length, 13);

    const vercelSug = suggestions.find((s) => s.id === "freellm-vercel-ai-gateway");
    ok("Vercel AI Gateway → sugerencia con getKeyUrl", vercelSug?.getKeyUrl === "https://vercel.com/docs/ai-gateway");
    ok("Vercel AI Gateway → limitsKind 'rate-limit' (es 'free', no trial)", vercelSug?.limitsKind === "rate-limit");

    const fwSug = suggestions.find((s) => s.name === "Fireworks");
    ok("Fireworks → limitsKind 'trial-credit'", fwSug?.limitsKind === "trial-credit");
    ok("Fireworks → limits refleja el crédito", fwSug?.limits === "$1");

    // "Mejores candidatos" == free REAL (no trial) + no curados aún → exactamente 2 hoy.
    const bestNew = suggestions.filter((s) => s.section === "free" && !s.alreadyInCatalog);
    eq(
      "candidatos nuevos elegibles (free, no curados)",
      bestNew.map((s) => s.id).sort(),
      ["freellm-opencode-zen", "freellm-vercel-ai-gateway"],
    );
  }

  console.log("\n[12] getFreeSourceSuggestions / refreshFreeSourcesFromLists — SSR-safe bajo Node (sin window)");
  {
    ok("getFreeSourceSuggestions() sin caché/window → []", getFreeSourceSuggestions().length === 0);
    ok(
      "getFreeSourceSuggestions({includeTrialCredits:true}) sin caché → []",
      getFreeSourceSuggestions({ includeTrialCredits: true }).length === 0,
    );
    const refreshResult = await refreshFreeSourcesFromLists();
    eq(
      "refreshFreeSourcesFromLists() sin window → no toca red, degrada a 'static'",
      refreshResult,
      { providers: 0, registered: 0, from: "static" },
    );
  }

  console.log(`\n${failed === 0 ? "✅" : "❌"} Free sources sync — ${passed} OK, ${failed} fallos\n`);
  if (failed > 0) process.exit(1);
}

void main();
