-- Add new values to widget_type enum
ALTER TYPE widget_type ADD VALUE IF NOT EXISTS 'SYSTEM_STATUS';
ALTER TYPE widget_type ADD VALUE IF NOT EXISTS 'RECENT_ACTIVITY';
ALTER TYPE widget_type ADD VALUE IF NOT EXISTS 'COLLAB_PROJECTS';
ALTER TYPE widget_type ADD VALUE IF NOT EXISTS 'LIVE_DATA';
-- Ensure THEME_SELECTOR exists if it was missed
ALTER TYPE widget_type ADD VALUE IF NOT EXISTS 'THEME_SELECTOR';
